// 164 cities @simplemaps 
// https://simplemaps.com/data/world-cities 

const cities = [
    {
        "city": "Manila", 
        "lat": "14.5958", 
        "lng": "120.9772", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Manila", 
        "capital": "primary", 
        "population": "23088000", 
        "population_proper": "1780148"
    }, 
    {
        "city": "Quezon City", 
        "lat": "14.6333", 
        "lng": "121.0333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Quezon", 
        "capital": "admin", 
        "population": "2936116", 
        "population_proper": "2936116"
    }, 
    {
        "city": "Davao", 
        "lat": "7.0667", 
        "lng": "125.6000", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Davao", 
        "capital": "admin", 
        "population": "1632991", 
        "population_proper": "1632991"
    }, 
    {
        "city": "Caloocan City", 
        "lat": "14.6500", 
        "lng": "120.9667", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Caloocan", 
        "capital": "admin", 
        "population": "1583978", 
        "population_proper": "1583978"
    }, 
    {
        "city": "Cebu City", 
        "lat": "10.3000", 
        "lng": "123.9000", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cebu", 
        "capital": "admin", 
        "population": "922611", 
        "population_proper": "922611"
    }, 
    {
        "city": "Zamboanga City", 
        "lat": "6.9167", 
        "lng": "122.0833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Zamboanga", 
        "capital": "admin", 
        "population": "861799", 
        "population_proper": "861799"
    }, 
    {
        "city": "Taguig City", 
        "lat": "14.5167", 
        "lng": "121.0500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Taguig", 
        "capital": "admin", 
        "population": "804915", 
        "population_proper": "804915"
    }, 
    {
        "city": "Antipolo", 
        "lat": "14.5842", 
        "lng": "121.1763", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Rizal", 
        "capital": "admin", 
        "population": "776386", 
        "population_proper": "776386"
    }, 
    {
        "city": "Pasig City", 
        "lat": "14.5750", 
        "lng": "121.0833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Pasig", 
        "capital": "admin", 
        "population": "755300", 
        "population_proper": "755300"
    }, 
    {
        "city": "Cagayan de Oro", 
        "lat": "8.4833", 
        "lng": "124.6500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cagayan de Oro", 
        "capital": "admin", 
        "population": "675950", 
        "population_proper": "675950"
    }, 
    {
        "city": "City of Para\u00f1aque", 
        "lat": "14.4667", 
        "lng": "121.0167", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Para\u00f1aque", 
        "capital": "admin", 
        "population": "665822", 
        "population_proper": "665822"
    }, 
    {
        "city": "Dasmari\u00f1as", 
        "lat": "14.3294", 
        "lng": "120.9367", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cavite", 
        "capital": "", 
        "population": "659019", 
        "population_proper": "659019"
    }, 
    {
        "city": "Valenzuela", 
        "lat": "14.7000", 
        "lng": "120.9833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Valenzuela", 
        "capital": "admin", 
        "population": "620422", 
        "population_proper": "620422"
    }, 
    {
        "city": "Bacoor", 
        "lat": "14.4624", 
        "lng": "120.9645", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cavite", 
        "capital": "", 
        "population": "600609", 
        "population_proper": "600609"
    }, 
    {
        "city": "General Santos", 
        "lat": "6.1167", 
        "lng": "125.1667", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "General Santos", 
        "capital": "admin", 
        "population": "594446", 
        "population_proper": "594446"
    }, 
    {
        "city": "Las Pi\u00f1as City", 
        "lat": "14.4500", 
        "lng": "120.9833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Las Pi\u00f1as", 
        "capital": "", 
        "population": "588894", 
        "population_proper": "588894"
    }, 
    {
        "city": "Makati City", 
        "lat": "14.5500", 
        "lng": "121.0333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Makati", 
        "capital": "admin", 
        "population": "582602", 
        "population_proper": "582602"
    }, 
    {
        "city": "San Jose del Monte", 
        "lat": "14.8139", 
        "lng": "121.0453", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bulacan", 
        "capital": "", 
        "population": "574089", 
        "population_proper": "574089"
    }, 
    {
        "city": "Bacolod", 
        "lat": "10.6765", 
        "lng": "122.9509", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bacolod", 
        "capital": "admin", 
        "population": "561875", 
        "population_proper": "561875"
    }, 
    {
        "city": "Muntinlupa City", 
        "lat": "14.3833", 
        "lng": "121.0500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Muntinlupa", 
        "capital": "admin", 
        "population": "504509", 
        "population_proper": "504509"
    }, 
    {
        "city": "City of Calamba", 
        "lat": "14.2167", 
        "lng": "121.1667", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Laguna", 
        "capital": "", 
        "population": "454486", 
        "population_proper": "454486"
    }, 
    {
        "city": "Marikina City", 
        "lat": "14.6500", 
        "lng": "121.1000", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Marikina", 
        "capital": "admin", 
        "population": "450741", 
        "population_proper": "450741"
    }, 
    {
        "city": "Iloilo", 
        "lat": "10.7167", 
        "lng": "122.5667", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Iloilo", 
        "capital": "admin", 
        "population": "447992", 
        "population_proper": "447992"
    }, 
    {
        "city": "Pasay City", 
        "lat": "14.5500", 
        "lng": "121.0000", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Pasay", 
        "capital": "admin", 
        "population": "416522", 
        "population_proper": "416522"
    }, 
    {
        "city": "Angeles City", 
        "lat": "15.1472", 
        "lng": "120.5847", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Angeles", 
        "capital": "admin", 
        "population": "411634", 
        "population_proper": "411634"
    }, 
    {
        "city": "Lapu-Lapu City", 
        "lat": "10.3150", 
        "lng": "123.9761", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Lapu-Lapu", 
        "capital": "admin", 
        "population": "408112", 
        "population_proper": "408112"
    }, 
    {
        "city": "Imus", 
        "lat": "14.4297", 
        "lng": "120.9367", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cavite", 
        "capital": "", 
        "population": "403785", 
        "population_proper": "403785"
    }, 
    {
        "city": "Mandaluyong City", 
        "lat": "14.5833", 
        "lng": "121.0333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Mandaluyong", 
        "capital": "admin", 
        "population": "386276", 
        "population_proper": "386276"
    }, 
    {
        "city": "Malabon", 
        "lat": "14.6625", 
        "lng": "120.9567", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Malabon", 
        "capital": "admin", 
        "population": "365525", 
        "population_proper": "365525"
    }, 
    {
        "city": "Mandaue City", 
        "lat": "10.3333", 
        "lng": "123.9333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Mandaue", 
        "capital": "admin", 
        "population": "362654", 
        "population_proper": "362654"
    }, 
    {
        "city": "Santa Rosa", 
        "lat": "14.3167", 
        "lng": "121.1167", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Laguna", 
        "capital": "", 
        "population": "353767", 
        "population_proper": "353767"
    }, 
    {
        "city": "Baguio City", 
        "lat": "16.4152", 
        "lng": "120.5956", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Baguio", 
        "capital": "admin", 
        "population": "345366", 
        "population_proper": "345366"
    }, 
    {
        "city": "Iligan", 
        "lat": "8.2333", 
        "lng": "124.2500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Iligan", 
        "capital": "admin", 
        "population": "342618", 
        "population_proper": "342618"
    }, 
    {
        "city": "Tarlac City", 
        "lat": "15.4802", 
        "lng": "120.5979", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Tarlac", 
        "capital": "admin", 
        "population": "342493", 
        "population_proper": "342493"
    }, 
    {
        "city": "Butuan", 
        "lat": "8.9534", 
        "lng": "125.5288", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Butuan", 
        "capital": "admin", 
        "population": "337063", 
        "population_proper": "337063"
    }, 
    {
        "city": "Bi\u00f1an", 
        "lat": "14.3333", 
        "lng": "121.0833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Laguna", 
        "capital": "", 
        "population": "333028", 
        "population_proper": "333028"
    }, 
    {
        "city": "Lipa City", 
        "lat": "13.9411", 
        "lng": "121.1622", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Batangas", 
        "capital": "", 
        "population": "332386", 
        "population_proper": "332386"
    }, 
    {
        "city": "Batangas", 
        "lat": "13.7500", 
        "lng": "121.0500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Batangas", 
        "capital": "admin", 
        "population": "329874", 
        "population_proper": "329874"
    }, 
    {
        "city": "San Pedro", 
        "lat": "14.3583", 
        "lng": "121.0583", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Laguna", 
        "capital": "", 
        "population": "325809", 
        "population_proper": "325809"
    }, 
    {
        "city": "General Trias", 
        "lat": "14.3833", 
        "lng": "120.8833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cavite", 
        "capital": "", 
        "population": "314303", 
        "population_proper": "314303"
    }, 
    {
        "city": "Cabuyao", 
        "lat": "14.2750", 
        "lng": "121.1250", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Laguna", 
        "capital": "", 
        "population": "308745", 
        "population_proper": "308745"
    }, 
    {
        "city": "San Fernando", 
        "lat": "15.0333", 
        "lng": "120.6833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Pampanga", 
        "capital": "admin", 
        "population": "306659", 
        "population_proper": "306659"
    }, 
    {
        "city": "Cabanatuan City", 
        "lat": "15.4833", 
        "lng": "120.9667", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Nueva Ecija", 
        "capital": "", 
        "population": "302231", 
        "population_proper": "302231"
    }, 
    {
        "city": "Cotabato", 
        "lat": "7.2167", 
        "lng": "124.2500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cotabato", 
        "capital": "admin", 
        "population": "299438", 
        "population_proper": "299438"
    }, 
    {
        "city": "Cadiz", 
        "lat": "10.9587", 
        "lng": "123.3086", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Negros Occidental", 
        "capital": "", 
        "population": "283157", 
        "population_proper": "129053"
    }, 
    {
        "city": "Lucena", 
        "lat": "13.9333", 
        "lng": "121.6167", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Lucena", 
        "capital": "admin", 
        "population": "266248", 
        "population_proper": "266248"
    }, 
    {
        "city": "San Pablo", 
        "lat": "14.0667", 
        "lng": "121.3167", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Laguna", 
        "capital": "", 
        "population": "266068", 
        "population_proper": "266068"
    }, 
    {
        "city": "Tagum", 
        "lat": "7.4478", 
        "lng": "125.8078", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Davao del Norte", 
        "capital": "admin", 
        "population": "259444", 
        "population_proper": "259444"
    }, 
    {
        "city": "Puerto Princesa", 
        "lat": "9.7500", 
        "lng": "118.7500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Puerto Princesa", 
        "capital": "admin", 
        "population": "255116", 
        "population_proper": "255116"
    }, 
    {
        "city": "Malolos", 
        "lat": "14.8433", 
        "lng": "120.8114", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bulacan", 
        "capital": "admin", 
        "population": "252074", 
        "population_proper": "252074"
    }, 
    {
        "city": "Mabalacat", 
        "lat": "15.2167", 
        "lng": "120.5833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Pampanga", 
        "capital": "", 
        "population": "250799", 
        "population_proper": "250799"
    }, 
    {
        "city": "Navotas", 
        "lat": "14.6667", 
        "lng": "120.9417", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Navotas", 
        "capital": "admin", 
        "population": "249463", 
        "population_proper": "249463"
    }, 
    {
        "city": "Tacloban", 
        "lat": "11.2444", 
        "lng": "125.0039", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Tacloban", 
        "capital": "admin", 
        "population": "242089", 
        "population_proper": "242089"
    }, 
    {
        "city": "Olongapo", 
        "lat": "14.8333", 
        "lng": "120.2833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Olongapo", 
        "capital": "admin", 
        "population": "233040", 
        "population_proper": "233040"
    }, 
    {
        "city": "Talisay", 
        "lat": "10.2500", 
        "lng": "123.8333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cebu", 
        "capital": "", 
        "population": "227645", 
        "population_proper": "227645"
    }, 
    {
        "city": "Ormoc", 
        "lat": "11.0167", 
        "lng": "124.6167", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Ormoc", 
        "capital": "admin", 
        "population": "215031", 
        "population_proper": "215031"
    }, 
    {
        "city": "Meycauayan", 
        "lat": "14.7333", 
        "lng": "120.9500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bulacan", 
        "capital": "", 
        "population": "209083", 
        "population_proper": "209083"
    }, 
    {
        "city": "Marawi City", 
        "lat": "8.0000", 
        "lng": "124.3000", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Lanao del Sur", 
        "capital": "admin", 
        "population": "201785", 
        "population_proper": "201785"
    }, 
    {
        "city": "Pagadian", 
        "lat": "7.8333", 
        "lng": "123.4333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Zamboanga del Sur", 
        "capital": "admin", 
        "population": "199060", 
        "population_proper": "199060"
    }, 
    {
        "city": "Legazpi City", 
        "lat": "13.1333", 
        "lng": "123.7333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Albay", 
        "capital": "admin", 
        "population": "196639", 
        "population_proper": "196639"
    }, 
    {
        "city": "Naga City", 
        "lat": "13.6167", 
        "lng": "123.1667", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Naga", 
        "capital": "admin", 
        "population": "196003", 
        "population_proper": "196003"
    }, 
    {
        "city": "Malaybalay", 
        "lat": "8.1575", 
        "lng": "125.1278", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bukidnon", 
        "capital": "admin", 
        "population": "174625", 
        "population_proper": "174625"
    }, 
    {
        "city": "Dagupan City", 
        "lat": "16.0333", 
        "lng": "120.3333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Dagupan", 
        "capital": "admin", 
        "population": "171271", 
        "population_proper": "171271"
    }, 
    {
        "city": "Digos", 
        "lat": "6.7500", 
        "lng": "125.3500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Davao del Sur", 
        "capital": "admin", 
        "population": "169393", 
        "population_proper": "169393"
    }, 
    {
        "city": "Sorsogon", 
        "lat": "12.9667", 
        "lng": "124.0000", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Sorsogon", 
        "capital": "admin", 
        "population": "168110", 
        "population_proper": "168110"
    }, 
    {
        "city": "Roxas City", 
        "lat": "11.5833", 
        "lng": "122.7500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Capiz", 
        "capital": "admin", 
        "population": "167003", 
        "population_proper": "167003"
    }, 
    {
        "city": "Trece Martires City", 
        "lat": "14.2833", 
        "lng": "120.8667", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cavite", 
        "capital": "admin", 
        "population": "155713", 
        "population_proper": "155713"
    }, 
    {
        "city": "Surigao", 
        "lat": "9.7833", 
        "lng": "125.4833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Surigao del Norte", 
        "capital": "admin", 
        "population": "154137", 
        "population_proper": "154137"
    }, 
    {
        "city": "Tuguegarao", 
        "lat": "17.6167", 
        "lng": "121.7167", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cagayan", 
        "capital": "admin", 
        "population": "153502", 
        "population_proper": "153502"
    }, 
    {
        "city": "Ilagan", 
        "lat": "17.1333", 
        "lng": "121.8833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Isabela", 
        "capital": "admin", 
        "population": "145568", 
        "population_proper": "145568"
    }, 
    {
        "city": "Mati", 
        "lat": "6.9500", 
        "lng": "126.2333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Davao Oriental", 
        "capital": "admin", 
        "population": "141141", 
        "population_proper": "141141"
    }, 
    {
        "city": "Kidapawan", 
        "lat": "7.0083", 
        "lng": "125.0894", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cotabato", 
        "capital": "admin", 
        "population": "140195", 
        "population_proper": "140195"
    }, 
    {
        "city": "Santiago", 
        "lat": "16.6833", 
        "lng": "121.5500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Santiago", 
        "capital": "admin", 
        "population": "134830", 
        "population_proper": "134830"
    }, 
    {
        "city": "Calapan", 
        "lat": "13.3667", 
        "lng": "121.2000", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Oriental Mindoro", 
        "capital": "admin", 
        "population": "133893", 
        "population_proper": "133893"
    }, 
    {
        "city": "Dumaguete City", 
        "lat": "9.3103", 
        "lng": "123.3081", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Negros Oriental", 
        "capital": "admin", 
        "population": "131377", 
        "population_proper": "131377"
    }, 
    {
        "city": "Dipolog", 
        "lat": "8.5667", 
        "lng": "123.3333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Zamboanga del Norte", 
        "capital": "admin", 
        "population": "130759", 
        "population_proper": "130759"
    }, 
    {
        "city": "San Juan", 
        "lat": "14.6000", 
        "lng": "121.0333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "San Juan", 
        "capital": "admin", 
        "population": "122180", 
        "population_proper": "122180"
    }, 
    {
        "city": "San Fernando", 
        "lat": "16.6167", 
        "lng": "120.3167", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "La Union", 
        "capital": "admin", 
        "population": "121812", 
        "population_proper": "121812"
    }, 
    {
        "city": "City of Isabela", 
        "lat": "6.7000", 
        "lng": "121.9667", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Basilan", 
        "capital": "admin", 
        "population": "112788", 
        "population_proper": "112788"
    }, 
    {
        "city": "Laoag", 
        "lat": "18.2000", 
        "lng": "120.6000", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Ilocos Norte", 
        "capital": "admin", 
        "population": "111125", 
        "population_proper": "111125"
    }, 
    {
        "city": "Tagbilaran City", 
        "lat": "9.6500", 
        "lng": "123.8500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bohol", 
        "capital": "minor", 
        "population": "105051", 
        "population_proper": "105051"
    }, 
    {
        "city": "Catbalogan", 
        "lat": "11.7833", 
        "lng": "124.8833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Samar", 
        "capital": "admin", 
        "population": "103879", 
        "population_proper": "103879"
    }, 
    {
        "city": "Balanga", 
        "lat": "14.6833", 
        "lng": "120.5333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bataan", 
        "capital": "admin", 
        "population": "96061", 
        "population_proper": "96061"
    }, 
    {
        "city": "Masbate", 
        "lat": "12.3667", 
        "lng": "123.6167", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Masbate", 
        "capital": "admin", 
        "population": "95389", 
        "population_proper": "95389"
    }, 
    {
        "city": "Maasin", 
        "lat": "10.1333", 
        "lng": "124.8500", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Southern Leyte", 
        "capital": "admin", 
        "population": "85560", 
        "population_proper": "85560"
    }, 
    {
        "city": "Cabadbaran", 
        "lat": "9.1228", 
        "lng": "125.5346", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Agusan del Norte", 
        "capital": "admin", 
        "population": "73639", 
        "population_proper": "73639"
    }, 
    {
        "city": "Oroquieta", 
        "lat": "8.4833", 
        "lng": "123.8000", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Misamis Occidental", 
        "capital": "admin", 
        "population": "70757", 
        "population_proper": "70757"
    }, 
    {
        "city": "Borongan", 
        "lat": "11.6000", 
        "lng": "125.4333", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Eastern Samar", 
        "capital": "admin", 
        "population": "69297", 
        "population_proper": "69297"
    }, 
    {
        "city": "Tandag", 
        "lat": "9.0667", 
        "lng": "126.1833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Surigao del Sur", 
        "capital": "admin", 
        "population": "56364", 
        "population_proper": "56364"
    }, 
    {
        "city": "Vigan", 
        "lat": "17.5747", 
        "lng": "120.3869", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Ilocos Sur", 
        "capital": "admin", 
        "population": "53879", 
        "population_proper": "53879"
    }, 
    {
        "city": "Palayan City", 
        "lat": "15.5333", 
        "lng": "121.0833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Nueva Ecija", 
        "capital": "admin", 
        "population": "41041", 
        "population_proper": "41041"
    }, 
    {
        "city": "Catarman", 
        "lat": "12.4989", 
        "lng": "124.6377", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Northern Samar", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "La Trinidad", 
        "lat": "16.4556", 
        "lng": "120.5903", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Benguet", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Kalibo", 
        "lat": "11.7086", 
        "lng": "122.3648", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Aklan", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "San Jose", 
        "lat": "10.7450", 
        "lng": "121.9415", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Antique", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Daet", 
        "lat": "14.1122", 
        "lng": "122.9553", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Camarines Norte", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Virac", 
        "lat": "13.5848", 
        "lng": "124.2374", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Catanduanes", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Bayombong", 
        "lat": "16.4812", 
        "lng": "121.1497", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Nueva Vizcaya", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Jolo", 
        "lat": "6.0522", 
        "lng": "121.0022", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Sulu", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Bongao", 
        "lat": "5.0292", 
        "lng": "119.7731", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Tawi-Tawi", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Baclayon", 
        "lat": "9.6250", 
        "lng": "123.9109", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bohol", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Argao", 
        "lat": "9.8814", 
        "lng": "123.6007", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cebu", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Isulan", 
        "lat": "6.6294", 
        "lng": "124.6051", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Sultan Kudarat", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Candelaria", 
        "lat": "13.9311", 
        "lng": "121.4233", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Quezon", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "San Juan", 
        "lat": "13.8285", 
        "lng": "121.3931", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Batangas", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Tiaong", 
        "lat": "13.9638", 
        "lng": "121.3212", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Quezon", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Boac", 
        "lat": "13.4463", 
        "lng": "121.8400", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Marinduque", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Perez", 
        "lat": "14.1946", 
        "lng": "121.9264", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Quezon", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Tubod", 
        "lat": "8.0555", 
        "lng": "123.7904", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Lanao del Norte", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Mamburao", 
        "lat": "13.2233", 
        "lng": "120.5960", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Occidental Mindoro", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Nabunturan", 
        "lat": "7.6029", 
        "lng": "125.9629", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Compostela Valley", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Malita", 
        "lat": "6.4150", 
        "lng": "125.6117", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Davao Occidental", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Badian", 
        "lat": "9.8691", 
        "lng": "123.3947", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cebu", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Bangued", 
        "lat": "17.5982", 
        "lng": "120.6155", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Abra", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Mambajao", 
        "lat": "9.2504", 
        "lng": "124.7156", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Camiguin", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Naval", 
        "lat": "11.5612", 
        "lng": "124.3952", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Biliran", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Barobo", 
        "lat": "8.5365", 
        "lng": "126.1196", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Surigao del Sur", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Alcantara", 
        "lat": "9.9717", 
        "lng": "123.4028", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cebu", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Iba", 
        "lat": "15.3276", 
        "lng": "119.9780", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Zambales", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Lingayen", 
        "lat": "16.0218", 
        "lng": "120.2319", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Pangasinan", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Dauis", 
        "lat": "9.6253", 
        "lng": "123.8658", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bohol", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Romblon", 
        "lat": "12.5751", 
        "lng": "122.2708", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Romblon", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Lianga", 
        "lat": "8.6336", 
        "lng": "126.0947", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Surigao del Sur", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Dalaguete", 
        "lat": "9.7618", 
        "lng": "123.5332", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cebu", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Alabel", 
        "lat": "6.1018", 
        "lng": "125.2905", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Sarangani", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Padre Burgos", 
        "lat": "13.9226", 
        "lng": "121.8116", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Quezon", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Baler", 
        "lat": "15.7589", 
        "lng": "121.5607", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Aurora", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Maribojoc", 
        "lat": "9.7436", 
        "lng": "123.8429", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bohol", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Siquijor", 
        "lat": "9.2142", 
        "lng": "123.5150", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Siquijor", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Lagawe", 
        "lat": "16.8000", 
        "lng": "121.1192", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Ifugao", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Ipil", 
        "lat": "7.7844", 
        "lng": "122.5861", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Zamboanga Sibugay", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Basco", 
        "lat": "20.4486", 
        "lng": "121.9702", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Batanes", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Shariff Aguak", 
        "lat": "6.8647", 
        "lng": "124.4417", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Maguindanao", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Cabarroguis", 
        "lat": "16.5111", 
        "lng": "121.5212", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Quirino", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Jordan", 
        "lat": "10.6584", 
        "lng": "122.5963", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Guimaras", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Bontoc", 
        "lat": "17.0899", 
        "lng": "120.9780", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Mountain", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Kabugao", 
        "lat": "18.0231", 
        "lng": "121.1840", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Apayao", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Prosperidad", 
        "lat": "8.5800", 
        "lng": "125.8964", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Agusan del Sur", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Santa Cruz", 
        "lat": "14.1167", 
        "lng": "121.2833", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Laguna", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Koronadal", 
        "lat": "6.2541", 
        "lng": "124.9922", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "South Cotabato", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "San Jose", 
        "lat": "10.1800", 
        "lng": "125.5683", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Dinagat Islands", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Tabuk", 
        "lat": "17.4084", 
        "lng": "121.2785", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Kalinga", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Pili", 
        "lat": "13.7177", 
        "lng": "123.7448", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Camarines Sur", 
        "capital": "admin", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Buguey", 
        "lat": "18.2882", 
        "lng": "121.8331", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cagayan", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "San Antonio", 
        "lat": "13.8965", 
        "lng": "121.2902", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Quezon", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Hinatuan", 
        "lat": "8.3689", 
        "lng": "126.3352", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Surigao del Sur", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Lupon", 
        "lat": "6.8981", 
        "lng": "126.0096", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Davao Oriental", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Poblacion", 
        "lat": "6.8037", 
        "lng": "124.6367", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Sultan Kudarat", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Panay", 
        "lat": "11.5563", 
        "lng": "122.7910", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Capiz", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Magalang", 
        "lat": "15.2154", 
        "lng": "120.6617", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Pampanga", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Agdangan", 
        "lat": "13.8771", 
        "lng": "121.9131", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Quezon", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Monkayo", 
        "lat": "7.8170", 
        "lng": "126.0524", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Compostela Valley", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Tingloy", 
        "lat": "13.6609", 
        "lng": "120.8711", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Batangas", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Anda", 
        "lat": "9.7444", 
        "lng": "124.5754", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bohol", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Talipao", 
        "lat": "5.9764", 
        "lng": "121.1161", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Sulu", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Kabasalan", 
        "lat": "7.7981", 
        "lng": "122.7636", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Zamboanga Sibugay", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Sikatuna", 
        "lat": "9.6904", 
        "lng": "123.9730", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bohol", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Padre Burgos", 
        "lat": "10.0369", 
        "lng": "125.0192", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Southern Leyte", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Roseller Lim", 
        "lat": "7.6561", 
        "lng": "122.4671", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Zamboanga Sibugay", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Banaybanay", 
        "lat": "6.9623", 
        "lng": "126.0172", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Davao Oriental", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "President Quirino", 
        "lat": "6.7253", 
        "lng": "124.7382", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Sultan Kudarat", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Corella", 
        "lat": "9.6896", 
        "lng": "123.9197", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Bohol", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Madridejos", 
        "lat": "9.7912", 
        "lng": "123.3462", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Cebu", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }, 
    {
        "city": "Claveria", 
        "lat": "12.9035", 
        "lng": "123.2457", 
        "country": "Philippines", 
        "iso2": "PH", 
        "admin_name": "Masbate", 
        "capital": "minor", 
        "population": "", 
        "population_proper": ""
    }
]

// console.log(cities.length);

module.exports = cities;
