module.exports.descriptors = [
    'Sampaguita',
    'Paru-paro',
    'Makiling',
    'Coral',
    'Marina',
    'Galeria',
    'Musika',
    'Karaoke',
    'Agosto',
    'Luna',
    'Mabini',
    'Mabukid',
    'Katahimikan',
    'Makinang',
    'Liwanag',
    'Marilag',
    'Dalisay',
    'Marahuyo',
    'Bituin',
    'Luntian',
    'Diwata',
    'Bahaghari',
    'Rosas',
    'Ningning',
    'Kutitap',
    'Narra',
    'Mariposa',
    'Marikit',
    'Tiktilaok',
    'Sinagtala',
    'Halakhak',
    'Muni-muni',
    'Maharlika',
    'Tadhana',
    'Kokak',
    'Sitsiritsit',
    'Salaginto',
    'Salagubang',
    'Tsokolate',
    'Mansanas',
    'Papaya',
    'Avocado',
    'Alateris',
    'Mangosteen',
    'Mutya',
    'Amihan',
    'Harana',
    'Tuliro',
    'Tatsulok',
    'Deadma',
    'Doo Bi Doo',
    'Silvertoes',
    'Nakapagtataka',
    'Beer',
    'Tulog Na',
    'Ligaya',
    'Akala',
    'Anting-anting',
    'Pasubali',
    'Lihim',
    'Huling Sayaw',
    'Alapaap',
    'Nobela',
    'Sandalan',
    'Picha Pie',
    'Gitara',
    'Pare Ko',
    'Halaga',
    'Kundiman',
    'Jeepney',
    'Paraluman',
    'Kisapmata',
    'Umaaraw Umuulan',
    'Antukin',
    'Abot Kamay',
    'Dragonfly',
    'Butterflies',
    'Gemini',
    'With a Smile',
    'Sampip',
    'Balisong',
    'Alas Onse',
    'Tagu-taguan',
    'Malaya',
    'Tangerine',
    'Burnout',
    'Sinigang',
    'Kare-kare',
    'Halo-halo',
    'Adobo',
    'Empanada',
    'Bibingka',
    'Suman',
    'Coconut',
    'Ensaymada',
    'Champorado',
    'Turon',
    'Pan de Sal',
    'Ube Halaya',
    'Pinipig',
    'Banana Cue',
    'Silvanas',
    'Bucayo',
    'Maja Blanca',
    'Kalamay',
    'Espasol',
    'Latik',
    'Maruya',
    'Sapin-sapin',
    'Bilo-bilo',
    'Palabok',
    'Buko Pie',
    'Kutsinta',
    'Gulaman',
    'Nata de coco',
    'Sorbetes',
    'Torete',
    'Panalangin',
    'Chinito',
    'Salamat',
    'Tabing Ilog',
    'Sa Kanya',
    'Kailan',
    'Ikaw',
    'Para sa Akin',
    'Kaleidoscope',
    'Pasakalye',
    'Oks Lang',
    'Sundo',
    'Isang Lahi',
    'Kanlungan',
    'Dukha',
    'Pumapatak Ulan',
    'Tondo',
    'Lando',
    'Marlboro',
    'Mag-isa',
    'Languyin',
    'Prodigals',
    'Leaves',
    'Lovestruck',
    'Over October',
    'Ben Ben',
    'Ridleys',
    'Parokya',
    'Eraserhead',
    'Gracenote',
    'Up Dharma',
    'Session Road',
    'Imago',
    'Sponge Cola',
    'Moonstar',
    'Kitchie',
    'Zelle',
    'Kamikazee',
    'Bamboo',
    'Rocksteddy',
    'Silent',
    'Itchyworm',
    'Sugarfree',
    'Magasin',
    'Buloy',
    'Zia',
    'Yeng',
    'The Ransom',
    'Moira',
    'Sitti',
    'Rivermaya',
    'Oranges Lemon',
    'Cueshe',
    'Meagan Trees',
    'Joslin',
    'Marion',
    'Franco',
    'Typecast',
    'Chicosci'
]

module.exports.places = [
    'Sanctuary',
    'Skies',
    'Tides',
    'Island',
    'Volcano Island',
    'Mountain',
    'Volcano',
    'Cove',
    'Cave',
    'Beach',
    'Archipelago',
    'River',
    'Camp',
    'Camp Site',
    'Paradise',
    'Haven',
    'Gardens',
    'Farm',
    'Resort',
    'Bay',
    'Hills',
    'Nature Park',
    'Eco Park',
    'Strait',
    'Village',
    'River',
    'Creek',
    'Creekside',
    'Springs',
    'Bayshore',
    'Sands',
    'Cliffs',
    'Shores',
    'Seas',
    'Seaside',
    'Forest',
    'Jungle',
    'Falls',
    'Riverdale',
    'Riverside',
    'Hot Springs',
    'Lake',
    'Lakeside'
]

