module.exports.descriptors = [
    'Sampaguita',
    'Paru-paro',
    'Makiling',
    'Ipininta',
    'Coral',
    'Prinsipe',
    'Prinsesa',
    'Marina',
    'Galeria',
    'Musika',
    'Karaoke',
    'Agosto',
    'Luna',
    'Mabini',
    'Mabukid',
    'Kalaliman',
    'Katahimikan',
    'Makinang',
    'Liwanag',
    'Ligaya',
    'Kadiliman',
    'Kapintasan',
    'Marilag',
    'Dalisay',
    'Marahuyo',
    'Bituin',
    'Luntian',
    'Diwata',
    'Bahaghari',
    'Paraluman',
    'Rosas',
    'Ningning',
    'Kutitap',
    'Narra'
]

module.exports.places = [
    'Island',
    'Volcano Island',
    'Mountain',
    'Volcano',
    'Cove',
    'Cave',
    'Beach',
    'Archipelago',
    'River',
    'Camp',
    'Camp Site',
    'Paradise',
    'Heaven',
    'Gardens',
    'Farm',
    'Resort',
    'Bay',
    'Hills',
    'Nature Park',
    'Eco Park',
    'Strait',
    'Village',
    'River',
    'Creek',
    'Creekside',
    'Springs',
    'Bayshore',
    'Sands',
    'Cliffs',
    'Shores'
]

